[package]
name = "roaring"
version = "0.6.0"
authors = ["Wim Looman <wim@nemo157.com>"]
description = "http://roaringbitmap.org : A better compressed bitset - pure Rust implementation "

documentation = "https://nemo157.com/roaring-rs"
repository = "https://github.com/Nemo157/roaring-rs"

readme = "README.md"
keywords = ["roaring", "data-structure", "bitmap"]
categories = ["data-structures"]
edition = "2018"

license = "MIT/Apache-2.0"

[badges]
travis-ci = { repository = "Nemo157/roaring-rs" }

[dependencies]
byteorder = "1.0"

[dev-dependencies]
"bencher" = "0.1.5"

[[bench]]
name = "lib"
harness = false